# frozen_string_literal: true

require 'rumale'
require 'numo/narray'
require 'date'
require 'fileutils'

namespace :ml do
  desc "Train the dropout prediction model using synthetic data"
  task train: :environment do
    TRAINING_SAMPLES = 50_000
    MODEL_FILE = Rails.root.join('lib', 'ml', 'dropout_model.marshal')
    TOTAL_WEEKS = 15 # Assumption for training context

    puts "Generating #{TRAINING_SAMPLES} synthetic training samples using StudentSimulator..."

    FileUtils.mkdir_p(File.dirname(MODEL_FILE))

    items = []
    simulator = StudentSimulator.new(TOTAL_WEEKS)

    TRAINING_SAMPLES.times do |i|
      # 1. Pick a random persona based on distribution
      # We simulate "picking a student" by using the index-based assignment
      # shuffling the index ensures we sample the whole distribution
      persona = simulator.assign_persona(rand(0...1000), 1000)
      
      # 2. Pick a random week in the semester
      week_num = rand(0...TOTAL_WEEKS)
      
      # 3. Generate random student specifics for variety
      specs = {
        personal_trend: rand(-0.08..0.08),
        boost_weeks: [], # Simplified for training samples
        rough_weeks: []
      }
      
      # 4. Simulate behavior
      activities = simulator.simulate_week(persona, week_num, specs)
      
      # 5. Calculate Features (Percentage of target)
      # Targets: Class(3), Assign(2), Parent(2) -> Indices 0, 1, 4 in Simulator
      
      # Helper to trust the simulator's output but normalize to %
      calc_pct = ->(actual, expected) { [((actual.to_f / expected) * 100), 100].min }
      
      class_pct = calc_pct.call(activities['class_attended'], 3)
      assign_pct = calc_pct.call(activities['assignment_submitted'], 2)
      parent_pct = calc_pct.call(activities['parent_login'], 2)
      
      # 6. Calculate Score Delta (Proxy)
      # High engagement usually means improving score, low means dropping
      # We approximate this relationship based on the persona for training labels
      score_delta = case persona
      when :star_student, :engaged then rand(-100..500)
      when :moderate then rand(-500..100)
      else rand(-1500..-200)
      end

      # 7. Determine Label (Risk)
      # High Risk = 1, Low Risk = 0
      # Disengaged/Inconsistent are high risk
      is_at_risk = [:disengaged, :inconsistent].include?(persona) ? 1 : 0
      
      # Add noise to label (5% chance of mislabeling to make model robust)
      label = (rand < 0.05) ? (1 - is_at_risk) : is_at_risk

      items << {
        features: [class_pct, assign_pct, parent_pct, score_delta],
        label: label,
        timestamp: Date.today # Placeholder, not used for training split anymore
      }
    end

    # Chronological split for realistic validation
    # (shuffling because we generated by loop, though random access)
    items.shuffle!
    split_idx = (items.size * 0.8).to_i
    train = items[0...split_idx]
    test  = items[split_idx..-1]

    x_train = Numo::DFloat.cast(train.map { |s| s[:features] })
    y_train = Numo::Int32.cast(train.map { |s| s[:label] })
    x_test  = Numo::DFloat.cast(test.map { |s| s[:features] })
    y_test  = Numo::Int32.cast(test.map { |s| s[:label] })

    puts "Training on #{x_train.shape[0]} samples..."

    scaler = Rumale::Preprocessing::StandardScaler.new
    x_train_scaled = scaler.fit_transform(x_train)
    x_test_scaled  = scaler.transform(x_test)

    # Using Random Forest to handle the non-linear relationship of "Declining" students
    model = Rumale::Ensemble::RandomForestClassifier.new(
      n_estimators: 150, # Increased for better stability
      max_depth: 10,
      max_features: 2,
      random_seed: 42
    )

    model.fit(x_train_scaled, y_train)

    # Evaluation
    preds = model.predict(x_test_scaled)
    tp = (preds.eq(1) & y_test.eq(1)).count
    fp = (preds.eq(1) & y_test.eq(0)).count
    fn = (preds.eq(0) & y_test.eq(1)).count
    tn = (preds.eq(0) & y_test.eq(0)).count

    accuracy = (tp + tn).to_f / y_test.size
    precision = tp.to_f / (tp + fp)

    puts "\n=== RETRAINED MODEL PERFORMANCE ==="
    puts "Accuracy:  #{(accuracy * 100).round(2)}%"
    puts "Precision: #{(precision * 100).round(2)}% (Predicting churn correctly)"
    puts "True Positives: #{tp} | False Positives: #{fp}"

    # Save payload
    File.binwrite(MODEL_FILE, Marshal.dump({ model: model, scaler: scaler }))
    puts "\n✓ Model updated at #{MODEL_FILE}"
  end
end
