// JsFromRoutes CacheKey ebbc13d670f5851def844e0557f3682f
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as dashboardOverview } from './Dashboard/OverviewApi'
export { default as dashboardStudents } from './Dashboard/StudentsApi'
export { default as dashboardCohorts } from './Dashboard/CohortsApi'
export { default as railsHealth } from './Rails/HealthApi'
