// JsFromRoutes CacheKey a9c28b9c4c5fd0ad04021e282ebdba2f
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/dashboard/cohorts'),
  show: /* #__PURE__ */ definePathHelper('get', '/dashboard/cohorts/:id'),
}
