// JsFromRoutes CacheKey 0e9747c0c5d1ac5fb536dfa60e914fb2
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  platform: /* #__PURE__ */ definePathHelper('get', '/dashboard/overview/platform'),
  student: /* #__PURE__ */ definePathHelper('get', '/dashboard/overview/student'),
  cohort: /* #__PURE__ */ definePathHelper('get', '/dashboard/overview/cohort'),
  mlPipeline: /* #__PURE__ */ definePathHelper('get', '/dashboard/overview/ml_pipeline'),
}
