// JsFromRoutes CacheKey 722fa622507ecd0c37a16d6c4915d29c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/dashboard/students'),
  show: /* #__PURE__ */ definePathHelper('get', '/dashboard/students/:id'),
}
